# Generated by Django 4.2.16 on 2024-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, help_text='URL of the live website', max_length=500),
        ),
    ]
